Specialkost - test till daniel
solidfox/Gripsholmsskolan-Forms pull request #1
Opened 2017-01-18 15:51 UTC by AlexanderGrip

Tog väldigt lång tid att göra. Koden är med all säkerhet fel någonstans. Du får väldigt gärna kolla igenom den om du vill Jag förstår inte varför texten. Blir stor i bland. :( Sen glömde jag duplicatea skriftlig varning! men jag duplicateade den som jag hade skrivit i och då den inte var sparad (tror jag) så fick jag den tillbaka :)

2017-01-19 09:19 UTC, solidfox commented
Du verkar inte ha syndat specialkost blanketten innan du gjorde en pull request.

2017-01-19 09:19 UTC, solidfox commented
Syncat

2017-01-19 09:22 UTC, solidfox commented
Eller så har du bara inte commitat

2017-01-19 09:33 UTC, AlexanderGrip commented
Specialkosten testade jag att göra hemifrån.
Jag testar synka den igen sen hemma! jag gjorde en ny blankett för ny
anställda! och sparade den som html format för att jag ville testa och se
hur den blev!
tyvärr blev den uhm :(
Sådär!

2017-01-19 10:22 GMT+01:00 Daniel Schlaug <notifications@github.com>:

> Eller så har du bara inte commitat
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/solidfox/Gripsholmsskolan-Forms/pull/1#issuecomment-273721545>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYB721gGls2trZsSpKYiJZBaakvLe9kqks5rTytggaJpZM4LnC_h>
> .
>

2017-01-19 09:35 UTC, solidfox commented
Det går inte att visa dem som separata HTML dokument. Alla filer i de två mapparna måste också finnas på plats, annars blir det konstigt.

All the best,
Daniel Schlaug

Machine Learning Master Student
@ KTH Royal Institute of Technology

2017年1月19日 10:33 +0100 に AlexanderGrip <notifications@github.com> は書きました:
> Specialkosten testade jag att göra hemifrån.
> Jag testar synka den igen sen hemma! jag gjorde en ny blankett för ny
> anställda! och sparade den som html format för att jag ville testa och se
> hur den blev!
> tyvärr blev den uhm :(
> Sådär!
>
> 2017-01-19 10:22 GMT+01:00 Daniel Schlaug <notifications@github.com>:
>
> > Eller så har du bara inte commitat
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/solidfox/Gripsholmsskolan-Forms/pull/1#issuecomment-273721545>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe-auth/AYB721gGls2trZsSpKYiJZBaakvLe9kqks5rTytggaJpZM4LnC_h>
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub (https://github.com/solidfox/Gripsholmsskolan-Forms/pull/1#issuecomment-273723903), or mute the thread (https://github.com/notifications/unsubscribe-auth/AAS4dvoGyS6vw5jcYhbdHR-RkeSFbXvTks5rTy3NgaJpZM4LnC_h).
>
>
>

2017-01-19 09:37 UTC, AlexanderGrip commented
Åh. så jag måste "synka" "Blankett för nyanställda med mapparna css, images
och js?

2017-01-19 10:35 GMT+01:00 Daniel Schlaug <notifications@github.com>:

> Det går inte att visa dem som separata HTML dokument. Alla filer i de två
> mapparna måste också finnas på plats, annars blir det konstigt.
>
> All the best,
> Daniel Schlaug
>
> Machine Learning Master Student
> @ KTH Royal Institute of Technology
>
> 2017年1月19日 10:33 +0100 に AlexanderGrip <notifications@github.com> は書きました:
> > Specialkosten testade jag att göra hemifrån.
> > Jag testar synka den igen sen hemma! jag gjorde en ny blankett för ny
> > anställda! och sparade den som html format för att jag ville testa och se
> > hur den blev!
> > tyvärr blev den uhm :(
> > Sådär!
> >
> > 2017-01-19 10:22 GMT+01:00 Daniel Schlaug <notifications@github.com>:
> >
> > > Eller så har du bara inte commitat
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/solidfox/Gripsholmsskolan-Forms/pull/1#
> issuecomment-273721545>,
> > > or mute the thread
> > > <https://github.com/notifications/unsubscribe-auth/
> AYB721gGls2trZsSpKYiJZBaakvLe9kqks5rTytggaJpZM4LnC_h>
> > > .
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub (
> https://github.com/solidfox/Gripsholmsskolan-Forms/pull/1#
> issuecomment-273723903), or mute the thread (https://github.com/
> notifications/unsubscribe-auth/AAS4dvoGyS6vw5jcYhbdHR-
> RkeSFbXvTks5rTy3NgaJpZM4LnC_h).
>
> >
> >
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/solidfox/Gripsholmsskolan-Forms/pull/1#issuecomment-273724481>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYB72w9RajhMiF2TKsdWZzWvbKgv0Dehks5rTy5vgaJpZM4LnC_h>
> .
>

2017-01-19 14:41 UTC, solidfox requested changes
La in lite kommentarer, tror du kan ändra på en massa andra ställen med samma typ av fel när du fixat dessa. Du kan också ta bort alla id="???". De bara stökar till det.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +					<tr
Ta bort <tr

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +					<label>Uppgifter om Eleven</label>
Uppgifter om Eleven ska vara en h2, inte en label.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +							<label>För- och efternamn</label>
Dela upp i två celler. En för förnamn och en för efternamn.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +			</tr>
Indentera! (Lägg på en tabb innan.)

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +					<td id="socialsecuritynumber">
Ta bort id.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +				<td id="name">
Ta bort id

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +				<td id="socialsecuritynumber">
Ta bort id

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +			<tr
Ta bort <tr

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +			<label>Eleven är allergisk mot</label>
Detta ska vara en h2, inte en label.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +<input type="checkbox" name="vehicle" value="Bike">
Fixa så det ser snyggt ut med indenteringen (tabbarna)

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +		<tr>
Avsluta förra raden med </tr> och ta bort en tab på  denna.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +		<label>Annat:</label>
Ta bort checkboxen helt och hållet.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +			<textarea rows=1></textarea>
Du måste avsluta `<td>` här.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +			<form action="">
Använd inte `<form>` (i dagsläget)

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +			<input type="checkbox" name="vehicle" value="Bike">
Ta bort name="vehicle" value="Bike" på alla checkboxes.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +</tr>
Indentering. Härifrån och neråt.

2017-01-19 14:41 UTC, solidfox commented on Specialkost.html
> +		<label>Annat:</label>
Och ta bort : från Annat:

2017-02-16 13:12 UTC, solidfox commented
"Mera" är inte det bästa att skriva på sin commit. Försök beskriva vad du gjort. T ex "Lagt till <label> taggar." eller "Ändrat <br> taggar till <li> taggar."

2017-02-16 17:21 UTC, AlexanderGrip commented
Det kan vara smart! Tack Daniel!
ska försöka komma i håg detta och tänka på! :)

ha en fin kväll :)

Den 16 februari 2017 14:12 skrev Daniel Schlaug <notifications@github.com>:

> "Mera" är inte det bästa att skriva på sin commit. Försök beskriva vad du
> gjort. T ex "Lagt till taggar." eller "Ändrat
> taggar till
> - taggar."
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/solidfox/Gripsholmsskolan-Forms/pull/1#issuecomment-280326484>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYB72_j73Ehb0q70jubdiWkp2bzQR-HYks5rdEsmgaJpZM4LnC_h>
> .
>

2017-03-01 14:27 UTC, merged